{% set name = "ncas-amof-netcdf-template" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ncas_amof_netcdf_template-{{ version }}.tar.gz
  sha256: 31de225d54459889633f66985c63f847d89d17380751050ca4890859f34a58a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - netcdf4
    - numpy
    - requests
    - pandas
    - pyyaml

test:
  imports:
    - ncas_amof_netcdf_template
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/joshua-hampton/ncas_amof_netcdf_template
  summary: Package to create NCAS AMOF netCDF files.
  license: MIT
  license_file: LICENSE
  doc_url: https://ncas-amof-netcdf-template.readthedocs.io/en/stable/index.html

extra:
  recipe-maintainers:
    - joshua-hampton
